#!/bin/bash

echo "#0 Install Dependencies"
echo
##################
# install build dependencies
#
##################
if [ -f /etc/debian_version ]; then 
    sudo apt-get install libopencv-*
elif [ -f /etc/redhat-release ]; then 
    sudo dnf install opencv
else 
    echo "Try installing packages manually. Not a deb / rpm based distribution"
    exit
fi

echo "#1 Build source files"
echo
##################
# build source - make
#
##################
cd src
make clean
if [ -z ${VIVI_SRC+x} ]; 
then 
	echo "VIVI_SRC is unset"
	echo "#2 Adding to ~/.bashrc"
	make && echo "export VIVI_SRC=`pwd`" >> ~/.bashrc
	source ~/.bashrc
else 
	echo "#2 VIVI_SRC is set to '$VIVI_SRC'"; fi
echo

echo "#3 Add execute permissions and copy vivi to /bin/"
echo
sudo chmod +X $VIVI_SRC/vivi
sudo chmod +X $VIVI_SRC/dissect/dissect
sudo cp $VIVI_SRC/vivi /bin/
echo


echo "------------- We are done here -------------"





